# Generated by Django 5.2.4 on 2025-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('start_time', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
            ],
        ),
    ]
