# Generated by Django 5.2.4 on 2025-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=50)),
                ('abbrev', models.CharField(max_length=15)),
                ('logo', models.CharField(max_length=50)),
                ('dark_logo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_id',
            field=models.IntegerField(default=0),
        ),
    ]
