# Generated by Django 5.2.4 on 2025-07-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_team_remove_game_away_team_remove_game_home_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='common_name',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dark_logo',
        ),
    ]
